# train/templates/training_script_template.py

def get_training_script_template(
    agent_name: str,
    model_path: str,
    train_file: str,
    val_file: str,
    config_path: str,
    result_dir: str
) -> str:
    """
    获取训练脚本模板
    
    :param agent_name: agent 名称
    :param model_path: 模型路径
    :param train_file: 训练数据文件路径
    :param val_file: 验证数据文件路径
    :param config_path: 配置文件路径
    :param result_dir: 结果输出目录
    :return: 脚本内容字符串
    """
    return f"""#!/bin/bash
# GRPO Training Script for {agent_name}
# Auto-generated by agent_client.py

set -e -x
export TORCH_COMPILE_DISABLE=1
export TORCH_DYNAMO_DISABLE=1
export VLLM_TORCH_COMPILE_DISABLE=1

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-12.4/lib64:/usr/lib/x86_64-linux-gnu
export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/cuda-12.4/lib64:/usr/lib/x86_64-linux-gnu

export RAY_RUNTIME_ENV_IGNORE_WEBHOOK=1
unset ROCR_VISIBLE_DEVICES

# Model Paths
export MODEL_PATH=${{MODEL_PATH:-{model_path}}}
export REWARD_MODEL_PATH=/home/ranhengwang/.cache/modelscope/hub/models/Qwen/Qwen3-8B
export RESULT_DIR=${{RESULT_DIR:-{result_dir}}}

python3 -m verl.trainer.main_ppo --config-name=rl_factory_ppo_trainer \\
    algorithm.adv_estimator=grpo\\
    data.train_files={train_file}\\
    data.val_files={val_file}\\
    data.train_batch_size=16\\
    data.max_prompt_length=4096\\
    data.max_response_length=512\\
    actor_rollout_ref.model.path=$MODEL_PATH\\
    actor_rollout_ref.model.use_remove_padding=True\\
    actor_rollout_ref.model.enable_gradient_checkpointing=True\\
    actor_rollout_ref.actor.optim.lr=1e-6\\
    actor_rollout_ref.actor.ppo_mini_batch_size=8\\
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=2\\
    actor_rollout_ref.actor.use_kl_loss=True\\
    actor_rollout_ref.actor.kl_loss_coef=0.001\\
    actor_rollout_ref.actor.kl_loss_type=low_var_kl\\
    actor_rollout_ref.actor.fsdp_config.param_offload=True\\
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True\\
    actor_rollout_ref.actor.state_masking=True\\
    actor_rollout_ref.actor.use_torch_compile=False\\
    actor_rollout_ref.ref.use_torch_compile=False\\
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=4\\
    actor_rollout_ref.rollout.tensor_model_parallel_size=1\\
    actor_rollout_ref.rollout.name=vllm\\
    actor_rollout_ref.rollout.gpu_memory_utilization=0.6\\
    actor_rollout_ref.rollout.n=4\\
    actor_rollout_ref.rollout.max_turns=2\\
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=4\\
    actor_rollout_ref.ref.fsdp_config.param_offload=True\\
    actor_rollout_ref.rollout.enforce_eager=False\\
    actor_rollout_ref.rollout.free_cache_engine=True\\
    actor_rollout_ref.env.name={agent_name}\\
    actor_rollout_ref.env.mcp_mode=stdio\\
    actor_rollout_ref.env.tool_manager=qwen3\\
    actor_rollout_ref.env.enable_thinking=False\\
    actor_rollout_ref.env.config_path={config_path}\\
    actor_rollout_ref.env.use_process_reward=True\\
    reward_rollout.if_use_reward_rollout=False\\
    reward_rollout.rollout.tensor_model_parallel_size=4\\
    reward_rollout.rollout.gpu_memory_utilization=0.6\\
    reward_rollout.rollout.model_name=$REWARD_MODEL_PATH\\
    reward_rollout.rollout.free_cache_engine=True\\
    reward_rollout.rollout.response_length=2048\\
    reward_model.reward_manager=parallel\\
    algorithm.kl_ctrl.kl_coef=0.001\\
    trainer.critic_warmup=0\\
    trainer.logger=['tensorboard']\\
    trainer.project_name='GRPO_{agent_name}'\\
    trainer.experiment_name='{agent_name}'\\
    trainer.n_gpus_per_node=2\\
    trainer.nnodes=1\\
    trainer.val_before_train=False\\
    trainer.default_local_dir=$RESULT_DIR\\
    trainer.default_hdfs_dir=null\\
    trainer.save_freq=20\\
    trainer.test_freq=10\\
    trainer.total_epochs=1 $@ 2>&1 | tee grpo.log
"""